[app]
mode = "release"
# 页面最大展示数据
pageMaxNum = 10
# jwt密钥
jwtSecret = ""
# 是否运行注册, 默认是禁止
register = false
[server]
port = 8080
[database]
# 数据库类型
driver = "mysql"
# sqlite
fileName = "sqlite.db"
# mysql
host = "127.0.0.1"
port = 3306
username = "root"
password = "123456"
# 数据库库名
name = "db_song_list"
